### ISSUE TITLE
There is no quit button

### ISSUE THREAD

**Issue by monkeyinsight** [monkeyinsight/postsmith#3]
Need to add button `q` for quitting application

```
KeyCode::Char('q') => {
   break Ok(());
}
```

I did this, but problem that inside input it tracks too, so you no longer can type `q` inside input. I think we need to move input to separate modal like here and have separate set of keystrokes for overall layout and modals:

<img width="1440" alt="image" src="https://github.com/monkeyinsight/postsmith/assets/2946657/c2dcea7d-09eb-449a-8066-11b695e79705">

**Comment by Danikxd** [comment]
![Screenshot from 2024-05-30 10-43-58](https://github.com/monkeyinsight/postsmith/assets/100193079/436426b8-0665-4a27-a79c-68866b888ff1)

I have quit button done on esc but i can transfer it to q button if that would be better
